#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# The three URLs Google needs to trust for redirects — the live Vercel URL
# we're testing on now, the real subdomain for once DNS is pointed, and
# localhost for local dev. Listing all three now avoids a second trip back
# into Google Cloud later.
REDIRECT_SIGNIN_1="https://sifarish-jobos-web.vercel.app/api/auth/callback/google"
REDIRECT_SIGNIN_2="https://sifarish.priyanshmathur.com/api/auth/callback/google"
REDIRECT_SIGNIN_3="http://localhost:3000/api/auth/callback/google"
REDIRECT_GMAIL_1="https://sifarish-jobos-web.vercel.app/api/gmail/callback"
REDIRECT_GMAIL_2="https://sifarish.priyanshmathur.com/api/gmail/callback"
REDIRECT_GMAIL_3="http://localhost:3000/api/gmail/callback"

banner "Sifarish: Google sign-in + Gmail setup"

# ── Stage 1: create/select the Google Cloud project ───────────────────────
stage "Google Cloud: project"
say "Everything below happens inside one Google Cloud project. If you don't"
say "have one for this yet, create it now; otherwise pick an existing one."
open_url "https://console.cloud.google.com/projectcreate"
step "Project name: something like 'Sifarish' (or reuse an existing project)."
step "Click Create, then wait for the notification bell to say it's ready."
step "Use the project picker at the top of the page to make sure that"
step "project is SELECTED before continuing to the next stage."
pause "Project created and selected?"

# ── Stage 2: OAuth consent screen ──────────────────────────────────────────
stage "OAuth consent screen"
say "This is the screen Google shows you when you sign in — it also gates"
say "which Google accounts are allowed to use the app while it's unverified."
open_url "https://console.cloud.google.com/apis/credentials/consent"
step "User Type: choose 'External', then Create."
step "App name: Sifarish"
step "User support email: your own email"
step "Developer contact email: your own email"
step "Save and continue through Scopes (skip, no changes needed)."
step "On the 'Test users' step, click + Add users and add your own Google"
step "account's email — this is REQUIRED while the app is in Testing mode,"
step "otherwise Google will refuse to let you sign in with it."
step "Save and continue to the summary, then Back to Dashboard."
pause "Consent screen configured with yourself as a test user?"

# ── Stage 3: enable the Gmail API ──────────────────────────────────────────
stage "Enable the Gmail API"
say "Needed so Sifarish can create Gmail drafts for outreach on your behalf."
open_url "https://console.cloud.google.com/apis/library/gmail.googleapis.com"
step "Make sure the same project from Stage 1 is selected (top bar)."
step "Click Enable (if it already says 'Manage', it's already on — skip)."
pause "Gmail API enabled?"

# ── Stage 4: create the OAuth client ───────────────────────────────────────
stage "Create OAuth 2.0 Client ID"
say "One client handles both sign-in and Gmail drafts — no need for two."
open_url "https://console.cloud.google.com/apis/credentials"
step "Click + Create Credentials → OAuth client ID."
step "Application type: Web application."
step "Name: Sifarish web"
step "Under 'Authorized redirect URIs', click + Add URI and add ALL SIX of"
step "these (one at a time — order doesn't matter):"
note "  $REDIRECT_SIGNIN_1"
note "  $REDIRECT_SIGNIN_2"
note "  $REDIRECT_SIGNIN_3"
note "  $REDIRECT_GMAIL_1"
note "  $REDIRECT_GMAIL_2"
note "  $REDIRECT_GMAIL_3"
step "Click Create. A dialog shows 'Your Client ID' and 'Your Client Secret'."
step "Keep that dialog open for the next stage (or reopen it by clicking the"
step "client's name in the credentials list, then 'Show secret')."
pause "Client created and the ID/secret dialog is visible?"

# ── Stage 5: capture the credentials ───────────────────────────────────────
stage "Copy the credentials"
say "Same client, same values, reused for both sign-in and Gmail — that's"
say "expected, not a mistake."
ask GOOGLE_CLIENT_ID "Paste the Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Client Secret:"
write_env AUTH_GOOGLE_ID "$GOOGLE_CLIENT_ID"
write_env AUTH_GOOGLE_SECRET "$GOOGLE_CLIENT_SECRET"
write_env GMAIL_OAUTH_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GMAIL_OAUTH_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
note ""
note "Next: copy these same four lines into Vercel → Settings → Environment"
note "Variables (same names), then redeploy. Sign-in and Gmail drafts both"
note "go live once that redeploy finishes."
# ──────────────────────────────────────────────────────────────────────────

finish
